/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.controlmastermind;

import javax.swing.JOptionPane;

/**
 *
 * @author Evese
 */
public class PanelPrincipalMastermind extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalMastermind
     */
    public int intentos = 0;
    public int intentosRestantes = 0;
    public String secuenciaComputadora[];
    public String strComputadora = "";
    public int estado = 0;
    
    
    public PanelPrincipalMastermind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btnComparar = new java.awt.Button();
        btnIniciar1 = new java.awt.Button();
        txtIntento = new java.awt.TextField();
        lblIntentosRestantes = new java.awt.Label();
        lblAciertoTotal = new java.awt.Label();
        lblAciertoParcial1 = new java.awt.Label();
        lblCantidadIntentos = new java.awt.Label();
        lblSecuenciaCaracteres = new java.awt.Label();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        label1.setText("Mastermind");

        btnComparar.setBackground(new java.awt.Color(244, 245, 126));
        btnComparar.setEnabled(false);
        btnComparar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnComparar.setLabel("Comparar");
        btnComparar.setName(""); // NOI18N
        btnComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompararMouseClicked(evt);
            }
        });
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        btnIniciar1.setBackground(new java.awt.Color(32, 215, 92));
        btnIniciar1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnIniciar1.setLabel("Iniciar");
        btnIniciar1.setName(""); // NOI18N
        btnIniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciar1MouseClicked(evt);
            }
        });
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });

        txtIntento.setBackground(new java.awt.Color(255, 204, 204));
        txtIntento.setEnabled(false);
        txtIntento.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntentoActionPerformed(evt);
            }
        });
        txtIntento.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtIntentoTextValueChanged(evt);
            }
        });

        lblIntentosRestantes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblIntentosRestantes.setText("Intentos restantes:");

        lblAciertoTotal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAciertoTotal.setText("Aciertos totales:");

        lblAciertoParcial1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAciertoParcial1.setText("Aciertos parciales:");

        lblCantidadIntentos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCantidadIntentos.setText("Cantidad de intentos:");

        lblSecuenciaCaracteres.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSecuenciaCaracteres.setText("Secuencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSecuenciaCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(btnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAciertoParcial1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAciertoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidadIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                                .addComponent(lblIntentosRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntentosRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lblSecuenciaCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAciertoParcial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAciertoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        label1.getAccessibleContext().setAccessibleName("lblTitulo");
    }// </editor-fold>//GEN-END:initComponents

    private void txtIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntentoActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    private void btnIniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciar1MouseClicked
           estado = 1;
           intentos = 1;
           intentosRestantes = 7;
           strComputadora = "";
           secuenciaComputadora = new String[4];
           crearColores();
           setIntentos();   
           btnComparar.setEnabled(true);
           txtIntento.setEnabled(true);           
           btnIniciar1.setEnabled(false); 
           lblAciertoParcial1.setText("Aciertos parciales: ");
           lblAciertoTotal.setText("Aciertos totales: ");
       
    }//GEN-LAST:event_btnIniciar1MouseClicked

    private void btnCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompararMouseClicked
        String letras = (txtIntento.getText().toUpperCase()).trim();
          
        int ap = 0;
        int at = 0;
        boolean validezLetras = letrasValidas(letras);
       
      
            if(letras.length() != 4 || !validezLetras){
                mostrarMensaje("Deben ser 4 letras cuáles quiera de A, B, R, N, V, M.");
                txtIntento.setText("");
            
            }else{
                                
               
                if(letras.equals(strComputadora)){                
                    mostrarMensaje("Felicidades, has ganado el juego");                
                    reiniciarValores();
                
                }else{
                    boolean apBool = false;
                    boolean atBool = false;
                    String arrLetras[] = letras.split("");
              
                    for(int u = 0; u< 4; u++){
                        apBool = false;
                        atBool = false;

                           for(int c = 0; c< 4; c++){
                                if( (arrLetras[u].equals(secuenciaComputadora[c])) && (u==c)){
                                    atBool = true;

                                }else if((arrLetras[u].equals(secuenciaComputadora[c])) && (u!=c)){
                                    apBool = true;
                                }
                            }

                           if(apBool){
                               ap++;
                           }
                           if(atBool){
                               at++;
                           }
                    }

                    lblAciertoParcial1.setText("Aciertos parciales: "+ap);
                    lblAciertoTotal.setText("Aciertos totales: "+at);
                
            }
            
            
             if(estado ==1){
                  intentosRestantes--;
                  intentos++;
                  setIntentos();
            }   
        
            if(intentosRestantes == 0 && estado == 1){
                mostrarMensaje("Lo sentimos, has perdido el juego.");
                reiniciarValores();
            }
        }
        
    }//GEN-LAST:event_btnCompararMouseClicked
    
    private boolean letrasValidas(String letras){ 
        String arrLetras[] = letras.split("");            
            for(String l : arrLetras){
                if(l.equals("A") ||
                        l.equals("R")||
                        l.equals("B")||
                        l.equals("N")||
                        l.equals("V")||
                        l.equals("M")){
                }else{
                    return false;
                }               
            }
            return true;
    }
    private void mostrarMensaje(String msj){
     JOptionPane.showMessageDialog(this, msj);
    }
    private void txtIntentoTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtIntentoTextValueChanged
        
    }//GEN-LAST:event_txtIntentoTextValueChanged
    
    private void setIntentos(){
         lblCantidadIntentos.setText("Intentos: "+String.valueOf(intentos));
         lblIntentosRestantes.setText("Intentos restantes: "+String.valueOf(intentosRestantes));
    }
    
    private void crearColores(){
        String colores[] = new String[6];
        colores[0] = "A";
        colores[1] = "B";
        colores[2] = "R";
        colores[3] = "N";
        colores[4] = "V";
        colores[5] = "M";             
           
        for (int i = 0; i < 4; i++) { 
            int num = (int)(Math.random() * ((6-1)+1)) + 1; 
            secuenciaComputadora[i]= colores[num-1];
            strComputadora += colores[num-1];
        }                 
    }
    
    private void reiniciarValores(){
           btnComparar.setEnabled(false);
           txtIntento.setEnabled(false);  
           txtIntento.setText("");
           btnIniciar1.setEnabled(true);            
           intentos = 0;
           intentosRestantes = 8;
           estado = 0;         
           
    
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnComparar;
    private java.awt.Button btnIniciar1;
    private java.awt.Label label1;
    private java.awt.Label lblAciertoParcial1;
    private java.awt.Label lblAciertoTotal;
    private java.awt.Label lblCantidadIntentos;
    private java.awt.Label lblIntentosRestantes;
    private java.awt.Label lblSecuenciaCaracteres;
    private java.awt.TextField txtIntento;
    // End of variables declaration//GEN-END:variables
}
